### ISSUE TITLE
Error After mirror large files, if small,  no error  After that it cannot be cancelled. only need to restart

### ISSUE THREAD

**Issue by kawinpattanai** [majnurangeela/mirror-hunter-upstream#6]
2022-06-19 08:39:27,141 - bot - INFO - Upload Name: Awaken-2.8-Plasma-a30-UNOFFICIAL-Vanilla-0742-20220615.zip
2022-06-19T08:39:27.141375+00:00 app[web.1]: 2022-06-19 08:39:27,141 - bot.helper.mirror_utils.upload_utils.gdriveTools - INFO - Authorizing with 13.json service account
2022-06-19T08:39:27.756052+00:00 app[web.1]: 2022-06-19 08:39:27,755 - bot.helper.mirror_utils.upload_utils.gdriveTools - INFO - Uploading File: /usr/src/app/downloads/4690/Awaken-2.8-Plasma-a30-UNOFFICIAL-Vanilla-0742-20220615.zip
2022-06-19T08:39:42.966591+00:00 app[web.1]: 2022-06-19 08:39:42,966 - bot.helper.mirror_utils.upload_utils.gdriveTools - INFO - Uploaded To G-Drive: /usr/src/app/downloads/4690/Awaken-2.8-Plasma-a30-UNOFFICIAL-Vanilla-0742-20220615.zip
2022-06-19T08:39:43.056666+00:00 app[web.1]: Exception in thread Thread-31 (onDownloadComplete):
2022-06-19T08:39:43.056682+00:00 app[web.1]: Traceback (most recent call last):
2022-06-19T08:39:43.056716+00:00 app[web.1]:   File "/usr/lib/python3.10/threading.py", line 1009, in _bootstrap_inner
2022-06-19T08:39:43.057083+00:00 app[web.1]:     self.run()
2022-06-19T08:39:43.057102+00:00 app[web.1]:   File "/usr/lib/python3.10/threading.py", line 946, in run
2022-06-19T08:39:43.057382+00:00 app[web.1]:     self._target(*self._args, **self._kwargs)
2022-06-19T08:39:43.057401+00:00 app[web.1]:   File "/usr/src/app/bot/modules/mirror.py", line 183, in onDownloadComplete
2022-06-19T08:39:43.058049+00:00 app[web.1]:     drive.upload(up_name)
2022-06-19T08:39:43.058071+00:00 app[web.1]:   File "/usr/src/app/bot/helper/mirror_utils/upload_utils/gdriveTools.py", line 272, in upload
2022-06-19T08:39:43.058755+00:00 app[web.1]:     self.__listener.onUploadComplete(link, size, self.__total_files, self.__total_folders, mime_type, self.name)
2022-06-19T08:39:43.058772+00:00 app[web.1]:   File "/usr/src/app/bot/modules/mirror.py", line 247, in onUploadComplete
2022-06-19T08:39:43.058964+00:00 app[web.1]:     reply_to.delete()
2022-06-19T08:39:43.058984+00:00 app[web.1]:   File "/usr/local/lib/python3.10/dist-packages/telegram/message.py", line 2431, in delete
2022-06-19T08:39:43.059565+00:00 app[web.1]:     return self.bot.delete_message(
2022-06-19T08:39:43.059584+00:00 app[web.1]:   File "/usr/local/lib/python3.10/dist-packages/telegram/bot.py", line 133, in decorator
2022-06-19T08:39:43.059720+00:00 app[web.1]:     result = func(*args, **kwargs)
2022-06-19T08:39:43.059738+00:00 app[web.1]:   File "/usr/local/lib/python3.10/dist-packages/telegram/bot.py", line 579, in delete_message
2022-06-19T08:39:43.059955+00:00 app[web.1]:     result = self._post('deleteMessage', data, timeout=timeout, api_kwargs=api_kwargs)
2022-06-19T08:39:43.059982+00:00 app[web.1]:   File "/usr/local/lib/python3.10/dist-packages/telegram/bot.py", line 298, in _post
2022-06-19T08:39:43.060129+00:00 app[web.1]:     return self.request.post(
2022-06-19T08:39:43.060146+00:00 app[web.1]:   File "/usr/local/lib/python3.10/dist-packages/telegram/utils/request.py", line 361, in post
2022-06-19T08:39:43.060315+00:00 app[web.1]:     result = self._request_wrapper(
2022-06-19T08:39:43.060334+00:00 app[web.1]:   File "/usr/local/lib/python3.10/dist-packages/telegram/utils/request.py", line 279, in _request_wrapper
2022-06-19T08:39:43.060478+00:00 app[web.1]:     raise BadRequest(message)
2022-06-19T08:39:43.060556+00:00 app[web.1]: telegram.error.BadRequest: Message can't be deleted

**Comment by codewithweeb** [comment]
there is no such error of big and small file cancel 
i had mirror the same file and didn't get any error
here is my log you can check it https://pastebin.com/wUHSktt0

**Comment by codewithweeb** [comment]
> 2022-06-19 08:39:27,141 - bot - INFO - Upload Name: Awaken-2.8-Plasma-a30-UNOFFICIAL-Vanilla-0742-20220615.zip 2022-06-19T08:39:27.141375+00:00 app[web.1]: 2022-06-19 08:39:27,141 - bot.helper.mirror_utils.upload_utils.gdriveTools - INFO - Authorizing with 13.json service account 2022-06-19T08:39:27.756052+00:00 app[web.1]: 2022-06-19 08:39:27,755 - bot.helper.mirror_utils.upload_utils.gdriveTools - INFO - Uploading File: /usr/src/app/downloads/4690/Awaken-2.8-Plasma-a30-UNOFFICIAL-Vanilla-0742-20220615.zip 2022-06-19T08:39:42.966591+00:00 app[web.1]: 2022-06-19 08:39:42,966 - bot.helper.mirror_utils.upload_utils.gdriveTools - INFO - Uploaded To G-Drive: /usr/src/app/downloads/4690/Awaken-2.8-Plasma-a30-UNOFFICIAL-Vanilla-0742-20220615.zip 2022-06-19T08:39:43.056666+00:00 app[web.1]: Exception in thread Thread-31 (onDownloadComplete): 2022-06-19T08:39:43.056682+00:00 app[web.1]: Traceback (most recent call last): 2022-06-19T08:39:43.056716+00:00 app[web.1]: File "/usr/lib/python3.10/threading.py", line 1009, in _bootstrap_inner 2022-06-19T08:39:43.057083+00:00 app[web.1]: self.run() 2022-06-19T08:39:43.057102+00:00 app[web.1]: File "/usr/lib/python3.10/threading.py", line 946, in run 2022-06-19T08:39:43.057382+00:00 app[web.1]: self._target(*self._args, **self._kwargs) 2022-06-19T08:39:43.057401+00:00 app[web.1]: File "/usr/src/app/bot/modules/mirror.py", line 183, in onDownloadComplete 2022-06-19T08:39:43.058049+00:00 app[web.1]: drive.upload(up_name) 2022-06-19T08:39:43.058071+00:00 app[web.1]: File "/usr/src/app/bot/helper/mirror_utils/upload_utils/gdriveTools.py", line 272, in upload 2022-06-19T08:39:43.058755+00:00 app[web.1]: self.__listener.onUploadComplete(link, size, self.__total_files, self.__total_folders, mime_type, self.name) 2022-06-19T08:39:43.058772+00:00 app[web.1]: File "/usr/src/app/bot/modules/mirror.py", line 247, in onUploadComplete 2022-06-19T08:39:43.058964+00:00 app[web.1]: reply_to.delete() 2022-06-19T08:39:43.058984+00:00 app[web.1]: File "/usr/local/lib/python3.10/dist-packages/telegram/message.py", line 2431, in delete 2022-06-19T08:39:43.059565+00:00 app[web.1]: return self.bot.delete_message( 2022-06-19T08:39:43.059584+00:00 app[web.1]: File "/usr/local/lib/python3.10/dist-packages/telegram/bot.py", line 133, in decorator 2022-06-19T08:39:43.059720+00:00 app[web.1]: result = func(*args, **kwargs) 2022-06-19T08:39:43.059738+00:00 app[web.1]: File "/usr/local/lib/python3.10/dist-packages/telegram/bot.py", line 579, in delete_message 2022-06-19T08:39:43.059955+00:00 app[web.1]: result = self._post('deleteMessage', data, timeout=timeout, api_kwargs=api_kwargs) 2022-06-19T08:39:43.059982+00:00 app[web.1]: File "/usr/local/lib/python3.10/dist-packages/telegram/bot.py", line 298, in _post 2022-06-19T08:39:43.060129+00:00 app[web.1]: return self.request.post( 2022-06-19T08:39:43.060146+00:00 app[web.1]: File "/usr/local/lib/python3.10/dist-packages/telegram/utils/request.py", line 361, in post 2022-06-19T08:39:43.060315+00:00 app[web.1]: result = self._request_wrapper( 2022-06-19T08:39:43.060334+00:00 app[web.1]: File "/usr/local/lib/python3.10/dist-packages/telegram/utils/request.py", line 279, in _request_wrapper 2022-06-19T08:39:43.060478+00:00 app[web.1]: raise BadRequest(message) 2022-06-19T08:39:43.060556+00:00 app[web.1]: telegram.error.BadRequest: Message can't be deleted

there is no such error of big and small file cancel
i had mirror the same file and didn't get any error
here is my log you can check it https://pastebin.com/wUHSktt0

**Comment by kawinpattanai** [comment]
I try again using leech&mirror stuck 100% upload why ? 

https://pastebin.com/xj78TczG

**Comment by kawinpattanai** [comment]
> > 2022-06-19 08:39:27,141 - bot - INFO - Upload Name: Awaken-2.8-Plasma-a30-UNOFFICIAL-Vanilla-0742-20220615.zip 2022-06-19T08:39:27.141375+00:00 app[web.1]: 2022-06-19 08:39:27,141 - bot.helper.mirror_utils.upload_utils.gdriveTools - INFO - Authorizing with 13.json service account 2022-06-19T08:39:27.756052+00:00 app[web.1]: 2022-06-19 08:39:27,755 - bot.helper.mirror_utils.upload_utils.gdriveTools - INFO - Uploading File: /usr/src/app/downloads/4690/Awaken-2.8-Plasma-a30-UNOFFICIAL-Vanilla-0742-20220615.zip 2022-06-19T08:39:42.966591+00:00 app[web.1]: 2022-06-19 08:39:42,966 - bot.helper.mirror_utils.upload_utils.gdriveTools - INFO - Uploaded To G-Drive: /usr/src/app/downloads/4690/Awaken-2.8-Plasma-a30-UNOFFICIAL-Vanilla-0742-20220615.zip 2022-06-19T08:39:43.056666+00:00 app[web.1]: Exception in thread Thread-31 (onDownloadComplete): 2022-06-19T08:39:43.056682+00:00 app[web.1]: Traceback (most recent call last): 2022-06-19T08:39:43.056716+00:00 app[web.1]: File "/usr/lib/python3.10/threading.py", line 1009, in _bootstrap_inner 2022-06-19T08:39:43.057083+00:00 app[web.1]: self.run() 2022-06-19T08:39:43.057102+00:00 app[web.1]: File "/usr/lib/python3.10/threading.py", line 946, in run 2022-06-19T08:39:43.057382+00:00 app[web.1]: self._target(*self._args, **self._kwargs) 2022-06-19T08:39:43.057401+00:00 app[web.1]: File "/usr/src/app/bot/modules/mirror.py", line 183, in onDownloadComplete 2022-06-19T08:39:43.058049+00:00 app[web.1]: drive.upload(up_name) 2022-06-19T08:39:43.058071+00:00 app[web.1]: File "/usr/src/app/bot/helper/mirror_utils/upload_utils/gdriveTools.py", line 272, in upload 2022-06-19T08:39:43.058755+00:00 app[web.1]: self.__listener.onUploadComplete(link, size, self.__total_files, self.__total_folders, mime_type, self.name) 2022-06-19T08:39:43.058772+00:00 app[web.1]: File "/usr/src/app/bot/modules/mirror.py", line 247, in onUploadComplete 2022-06-19T08:39:43.058964+00:00 app[web.1]: reply_to.delete() 2022-06-19T08:39:43.058984+00:00 app[web.1]: File "/usr/local/lib/python3.10/dist-packages/telegram/message.py", line 2431, in delete 2022-06-19T08:39:43.059565+00:00 app[web.1]: return self.bot.delete_message( 2022-06-19T08:39:43.059584+00:00 app[web.1]: File "/usr/local/lib/python3.10/dist-packages/telegram/bot.py", line 133, in decorator 2022-06-19T08:39:43.059720+00:00 app[web.1]: result = func(*args, **kwargs) 2022-06-19T08:39:43.059738+00:00 app[web.1]: File "/usr/local/lib/python3.10/dist-packages/telegram/bot.py", line 579, in delete_message 2022-06-19T08:39:43.059955+00:00 app[web.1]: result = self._post('deleteMessage', data, timeout=timeout, api_kwargs=api_kwargs) 2022-06-19T08:39:43.059982+00:00 app[web.1]: File "/usr/local/lib/python3.10/dist-packages/telegram/bot.py", line 298, in _post 2022-06-19T08:39:43.060129+00:00 app[web.1]: return self.request.post( 2022-06-19T08:39:43.060146+00:00 app[web.1]: File "/usr/local/lib/python3.10/dist-packages/telegram/utils/request.py", line 361, in post 2022-06-19T08:39:43.060315+00:00 app[web.1]: result = self._request_wrapper( 2022-06-19T08:39:43.060334+00:00 app[web.1]: File "/usr/local/lib/python3.10/dist-packages/telegram/utils/request.py", line 279, in _request_wrapper 2022-06-19T08:39:43.060478+00:00 app[web.1]: raise BadRequest(message) 2022-06-19T08:39:43.060556+00:00 app[web.1]: telegram.error.BadRequest: Message can't be deleted
> 
> there is no such error of big and small file cancel i had mirror the same file and didn't get any error here is my log you can check it https://pastebin.com/wUHSktt0

after stuck 100% upload  I can't cancel I can't cancel
